name: loader_overlay
description: A simple package to simplify screen management. When loading any async task, this package prevent the user from interacting with the screen until the async task finishes.
version: 4.0.0

homepage: https://github.com/rodrigobastosv/loading_overlay

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  back_button_interceptor: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4